######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 1 15:40:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += glwidget.h visao.h
FORMS += visao.ui
SOURCES += glwidget.cpp main.cpp visao.cpp
QT += opengl